apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  litellm_config.yaml: |
    model_list:
      - model_name: groq-llama3-8b
        litellm_params:
          model: groq/llama3-8b-8192
    env:
      passthrough: true
