apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rmk-ragbot-app
  namespace: argocd
spec:
  project: rmk-ragbot
  source:
    repoURL: https://github.com/AkkshayK-98/raspberry-pi5-gitops
    targetRevision: HEAD
    path: argo/apps/rmk-ragbot
  destination:
    server: https://kubernetes.default.svc
    namespace: rmk-ragbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true