apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ragbot-postgres
spec:
  serviceName: ragbot-postgres
  replicas: 1
  selector:
    matchLabels:
      app: ragbot-postgres
  template:
    metadata:
      labels:
        app: ragbot-postgres
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg16
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ragbot-postgres-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
